version: '3.8'

services:
  task_api:
    image: task_image
    container_name: task_api
    ports:
      - "7025:80"
    build:
      context: .
      dockerfile: Dockerfile

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: elbek
      MONGO_INITDB_ROOT_PASSWORD: elbek